'''
This modules add products to the products table, we can change
the product description and category later.
'''
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database.model import Product
from dotenv import load_dotenv

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)
Session = sessionmaker(bind=engine)
session = Session()

IMAGES_DIR = os.path.join(os.path.dirname(__file__), "static", "images")

def main():
    files = os.listdir(IMAGES_DIR)
    for f in files:
        if not (f.lower().endswith(".jpg") or f.lower().endswith(".png") or f.lower().endswith(".jpeg")):
            continue

        name = os.path.splitext(f)[0]  # product name from filename
        product = Product(
            name=name,
            category="General",
            image_filename=f,
            price=0.0,
            description="Autogenerated product."
        )

        session.add(product)
        print(f"Added product: {name}")

    session.commit()
    print("✅ All products added to database.")

if __name__ == "__main__":
    main()
